<?php

use Illuminate\Support\Facades\File;

beforeEach(function () {
    $this->dtoPath = app_path('DataTransferObjects');
    $this->typesPath = resource_path('js/types');

    // Clean up
    if (File::isDirectory($this->dtoPath)) {
        File::deleteDirectory($this->dtoPath);
    }
    if (File::isDirectory($this->typesPath)) {
        File::deleteDirectory($this->typesPath);
    }
});

afterEach(function () {
    if (File::isDirectory($this->dtoPath)) {
        File::deleteDirectory($this->dtoPath);
    }
    if (File::isDirectory($this->typesPath)) {
        File::deleteDirectory($this->typesPath);
    }
});

test('command is registered', function () {
    $this->artisan('types:generate --help')
        ->assertSuccessful();
});

test('warns when dto directory does not exist', function () {
    $this->artisan('types:generate')
        ->assertFailed();
});

test('succeeds with empty dto directory', function () {
    File::ensureDirectoryExists(app_path('DataTransferObjects'));

    $this->artisan('types:generate')
        ->assertSuccessful();
});

test('generates typescript from simple dto', function () {
    File::ensureDirectoryExists(app_path('DataTransferObjects'));

    $dtoContent = <<<'PHP'
<?php

declare(strict_types=1);

namespace App\DataTransferObjects;

final readonly class UserData
{
    public function __construct(
        public int $id,
        public string $name,
        public string $email,
    ) {}
}
PHP;

    File::put(app_path('DataTransferObjects/UserData.php'), $dtoContent);

    $this->artisan('types:generate')
        ->assertSuccessful();

    $typesFile = resource_path('js/types/generated.d.ts');
    expect(File::exists($typesFile))->toBeTrue();

    $content = File::get($typesFile);
    expect($content)->toContain('export interface UserData {');
    expect($content)->toContain('id: number;');
    expect($content)->toContain('name: string;');
    expect($content)->toContain('email: string;');
});

test('handles nullable types', function () {
    File::ensureDirectoryExists(app_path('DataTransferObjects'));

    $dtoContent = <<<'PHP'
<?php

declare(strict_types=1);

namespace App\DataTransferObjects;

final readonly class ProfileData
{
    public function __construct(
        public int $id,
        public ?string $bio,
        public ?int $age,
    ) {}
}
PHP;

    File::put(app_path('DataTransferObjects/ProfileData.php'), $dtoContent);

    $this->artisan('types:generate')
        ->assertSuccessful();

    $content = File::get(resource_path('js/types/generated.d.ts'));
    expect($content)->toContain('id: number;');
    expect($content)->toContain('bio?: string;');
    expect($content)->toContain('age?: number;');
});

test('converts php types to typescript', function () {
    File::ensureDirectoryExists(app_path('DataTransferObjects'));

    $dtoContent = <<<'PHP'
<?php

declare(strict_types=1);

namespace App\DataTransferObjects;

final readonly class TypesData
{
    public function __construct(
        public int $integer,
        public float $decimal,
        public bool $boolean,
        public string $text,
        public array $items,
    ) {}
}
PHP;

    File::put(app_path('DataTransferObjects/TypesData.php'), $dtoContent);

    $this->artisan('types:generate')
        ->assertSuccessful();

    $content = File::get(resource_path('js/types/generated.d.ts'));
    expect($content)->toContain('integer: number;');
    expect($content)->toContain('decimal: number;');
    expect($content)->toContain('boolean: boolean;');
    expect($content)->toContain('text: string;');
    expect($content)->toContain('items: unknown[];');
});

test('adds auto-generated header', function () {
    File::ensureDirectoryExists(app_path('DataTransferObjects'));

    $dtoContent = <<<'PHP'
<?php

declare(strict_types=1);

namespace App\DataTransferObjects;

final readonly class SimpleData
{
    public function __construct(
        public int $id,
    ) {}
}
PHP;

    File::put(app_path('DataTransferObjects/SimpleData.php'), $dtoContent);

    $this->artisan('types:generate')
        ->assertSuccessful();

    $content = File::get(resource_path('js/types/generated.d.ts'));
    expect($content)->toContain('Auto-generated by `php artisan types:generate`');
    expect($content)->toContain('Do not edit manually');
});

test('respects custom output path', function () {
    File::ensureDirectoryExists(app_path('DataTransferObjects'));

    $dtoContent = <<<'PHP'
<?php

declare(strict_types=1);

namespace App\DataTransferObjects;

final readonly class TestData
{
    public function __construct(
        public int $id,
    ) {}
}
PHP;

    File::put(app_path('DataTransferObjects/TestData.php'), $dtoContent);

    $customPath = 'resources/js/custom-types.d.ts';

    $this->artisan('types:generate', ['--output' => $customPath])
        ->assertSuccessful();

    expect(File::exists(base_path($customPath)))->toBeTrue();

    // Clean up custom path
    File::delete(base_path($customPath));
});

test('generates multiple interfaces', function () {
    File::ensureDirectoryExists(app_path('DataTransferObjects'));

    $userDto = <<<'PHP'
<?php

declare(strict_types=1);

namespace App\DataTransferObjects;

final readonly class UserData
{
    public function __construct(
        public int $id,
        public string $name,
    ) {}
}
PHP;

    $orderDto = <<<'PHP'
<?php

declare(strict_types=1);

namespace App\DataTransferObjects;

final readonly class OrderData
{
    public function __construct(
        public int $id,
        public int $total,
    ) {}
}
PHP;

    File::put(app_path('DataTransferObjects/UserData.php'), $userDto);
    File::put(app_path('DataTransferObjects/OrderData.php'), $orderDto);

    $this->artisan('types:generate')
        ->assertSuccessful();

    $content = File::get(resource_path('js/types/generated.d.ts'));
    expect($content)->toContain('export interface UserData {');
    expect($content)->toContain('export interface OrderData {');
});
